# Generated by Django 5.1.5 on 2025-03-09 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_language'),
        ('catalog', '0004_book_language'),
    ]

    operations = [
    ]
