# Generated by Django 5.1.5 on 2025-03-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_merge_0002_language_0004_book_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(help_text="Enter a book's language (e.g. English, Spanish, etc.)", max_length=200, unique=True),
        ),
    ]
